### ISSUE TITLE
Lessons

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/data-literacies#12]
I made some changes directly on the files (minor things: typos, links, punctuation, etc.) and here are some comments!

- [x] "Stages of Data" I like the conciseness, but might be useful to follow up with a bit of an narrative/real case scenario? 

- [x] "Raw Data" I think a concrete example would be helpful

- [x] In the  Challenge: for Raw Data and Labor // A possible question could be: "What are your practices to collect raw data?" Or something that would spark a reflection along those lines?  

- [x] Processed/Transformed section: Maybe add more examples, in addition to "table"? In that section, I think it would also be helpful to give a bit more of information on structured data formats (at least the ones you use in your example, otherwise it seems a bit abrupt... again, this is probably something we wouldn't write in our tutorials if we were conducting these workshops in person, as we'd have the opportunity to just come up with an example in person, but...)

- [x] Challenges: I wonder if some of the challenges could be more on the practical side? e.g., we can provide a simple dataset and ask participants how they would clean it (or even just ask them to describe it: is it consistent? is it valid? etc.)

- [x] Final activity: I wonder how you plan on conducting it in a remote learning environment? 

Formatting: 

- [x] I see when you use quotation marks you alternate ' with "  – I didn't fix it myself because I wasn't sure which one you wanted to use! 
- [x] Where you mention your sources, I think it might make sense to add the links to them? e.g., "Georgia Tech" but also in the table with data viz examples. I tried to add links myself in the latter, but for some reason, it didn't work in the captions? @kallewesterling 
- [x] Footnotes kinda look awkward (both in GitHub and even more when the file is rendered), I wonder if it makes more sense to add either smaller text below (in the "Small list of open formats," for example) or do parenthetical citation when needed? 

Hope this all makes sense, feel free to shoot me a message on Slack or comment here if you need clarifications on some/any comments!

**Comment by kallewesterling** [comment]
I agree with links being useful in the table of examples as well. I looked into the "links in captions" issue that @smorello87 mentions. I believe, because you are not generating the table as `markdown`, the `markdown` processor does not recognize inline `markdown` as anything but `html`. So the links would need to be hardcoded just like the table is.

For example (see [line 360](https://github.com/DHRI-Curriculum/data-literacies/blame/v2.0-di-edits/lessons.md#L360)):

```html
<td><img src="/images/D4PG_bar.png" alt="Bar Chart"><figcaption>From [The Data for Public Good](https://dataforgood.commons.gc.cuny.edu/) at the Graduate Center.</figcaption></td>
```

needs to be:

```html
<td><img src="/images/D4PG_bar.png" alt="Bar Chart"><figcaption>From <a href="https://dataforgood.commons.gc.cuny.edu" target="_blank">The Data for Public Good</a> at the Graduate Center.</figcaption></td>
```

**Comment by gofilipa** [comment]
This is going to be rather long, but that's mostly because I'm including some stuff that can be copy/pasted into the workshop if desired. 

First of all---excellent workshop! I like the progression, though I found the headings to be a little confusing (some smaller headings where I expected larger ones, like "tidy data" for example?), but maybe that's just me. 

I went ahead and changed one thing, some of the language of the "objectives" section in **Frontmatter**, in order to vary the use of the word "understand." 

Additionally, that page could use a bit more description for the "abstract", for example:

>What is data? Data is the foundation of nearly all digital humanities projects. In order to do digital work, we ought to know how data is captured, constructed, and manipulated. In this workshop we will be discussing the basics of research data, in terms of material, transformation, and presentation.

In **Lessons**, I have the following suggestions: 

**What Constitutes Research Data**: include a little intro here that explains what you're doing with these quotes, for example:

> The quotes below orient our understanding of what constitutes
research data. They come from various stakeholders to offer their own
definitions and approaches toward data.

**Forms of Data**: Here we jump to "after processing our data" without knowing what "processing data" means. Is there another way to phrase this? Maybe "Data can take take various forms, types, or manifestations" or something?

**Forms of Data: Challenge**: Include a solution, even if it's just to give an example of what this exercise might look like:

> Solution:

> 1. From the perspective of a literary researcher, my data takes the form of images (PDFs, JPEG) of archival materials, as well as digitized or encoded text in TEI format (XML). It also includes regular print books (of course!) and ebooks (like epub and mobi). 
   
> 2. Most people in literary studies are working with print or digitized books and journals. 
   
> 3. I get my data mostly from libraries and archives, either in person or digitized materials. 
   
**Stages of Data: Raw**: A great resource by Johanna Drucker could go here, in case people want to dive deeper into the ethics of "raw" data. [Drucker's article](http://www.digitalhumanities.org/dhq/vol/5/1/000091/000091.html) makes the distinction between "data" (given) and "capta" (taken or "captured"), in a way that troubles the distinction between "raw" and "cooked" data. 

**Stages of Data: Challenge**: Not 100 percent sure what this question is asking in this current form (could be just me!). But I took a stab at some revision that might clarify:

> Think about the similarities and differences between 'Big Data' and 'Raw Data'. Why does the quantity of data play into our assumptions about its 'rawness'? How should we define and approach data that is scraped or large in quantity?

**Processed/Transformed** : Agreed with Stefano that using an example as a way to thread through this demonstration would be useful. Maybe grabbing a dataset from somewhere and using screenshots to show them what raw data looks like? Also agreed with S that a little more info on the differences between these major file types is needed, especially since this is asynchronous. Here's some stuff I wrote up that you can copy/paste into the lesson:

> XML: Or eXstensible Markup Language, uses a nested structure, where the "tags" like `<Cat>` contain other tags inside them, like `<firstName>`. This format is good for organizing the layout of a document in a tree-like format, just like HTML, where we want to nest elements like a sentence within a paragraph, for example.

> JSON: Or JavaScript Object Notation, also uses a nesting structure, but with the addition of "key/value" pairs, like the `firstName` key which is tied to the `Smally` value (at least for the first cat!). JSON is popular with web applications that save and send data from your browser to web servers, because it uses the main language of web browsers, JavaScript, to work with data.

> CSV: Or Comma Separated Values uses---you guessed it!---commas to separate values. Each line (`First Name, Last Name`) is a new "record" and each column (separated by a comma) is a new "field." This data format stores tabular data it a clean way that facilitates the transfer of data between different data architectures. As data types go, it is very rudimentary (even predating computers!) and is easy to type, without needing special characters beyond a comma.

**Visualized: Challege # 2**:  Maybe link here to *[Voyant-Tools](https://voyant-tools.org/)*, an excellent text-analysis tool that's often used to "quantify" novels and allows for word clouds / heat maps like you mention. Also a really fun interface to play around with.

**Generally, on Challenges**: As of now, many of the challenges consist of open ended questions. While this does a good job of getting participants to consider things they haven't yet thought about, it also might lack adequate guidance for beginners. 

So the question is how do we scaffold their thinking and engagement on working with data? I think Stefano's suggestion about having a practical element in the challenges would be beneficial (I'm thinking particularly for "More Stages of Data: When do we Stop Cleaning?" and "Analyzed"). Maybe there can be one dataset that will establish a touchstone for many of the challenges, so you have something concrete to point your participants toward?  Another option would be to write
solutions to the challenges, even if they are just one person's speculation. This would allow the participants to engage with at least another person about these questions. I am willing to write up some solutions to this effect, so let me know (see a sample of this on the "Stages of Data" challenge).

**Finally**, the table in "Visualized" is beautiful, and the last activity is so interesting! I'm glad they will be in groups (of two, I believe?) to do it.

**Comment by dyoong** [comment]
Thanks for the comments and the help in shaping the repo! I really appreciate your time. I am definitely inclined to a more practical/hands-on activity. The only thing is that I am having trouble choosing an appropriate file that will require little resources on the part of the participants. Any suggestions from either/all of you would be great. In the meantime I have added the suggested solutions for each challenge.

**Comment by kallewesterling** [comment]
Tagging everyone here so they can chip in! @lmrhody @gofilipa @smorello87 @paramajmera @hackettka @rafadavis @szweibel

**Comment by smorello87** [comment]
Maybe an inconsistent set addresses? Say, 10-15 of them? E.g., some missing
information such as Zip Code, or State; some with towns reported
inconsistently (e.g. New York VS New York City VS Manhattan or Queens VS
Flushing); some with five digits and others with five-four zip codes, etc.

**Comment by kallewesterling** [comment]
I like that idea @smorello87. I can also imagine something like a list of bibliographic references (although, because the variety can be extremely vast there, it might be too complicated)... But it would play off of @gofilipa's idea in the `python` workshop, for instance in her [`for <variable name> in <list name>: <do something>` example](https://github.com/DHRI-Curriculum/python/blob/v2.0-filipa-edits/lessons.md#loops)!

**Comment by dyoong** [comment]
Given what was discussed in the meeting today + the incorporation of a more practical manipulation, would you all think that having the bulk of the questions be placed in the self-reflection section at the end (in assessment) be better? Otherwise would the challenge section in the session be too overwhelming? Or I can also include a reflection section in the lesson where the questions will live, and the challenge section where the practical application will be?

**Comment by kallewesterling** [comment]
I think open-ended question under `## Challenge` inside a lesson is still good. What you could do in a `## Solution` section is to provide some guidance to other websites/videos/tutorials or what have you, where folks can follow up if they want to... What do you think about that @dyoong?

**Comment by dyoong** [comment]
I have drafted solutions to the existing open-ended questions under challenges as per Filipa's previous suggestions. I was just wondering if it should be in a different section from an application-focused challenge only because I'm not sure if it will be confusing format wise to have reflection and application together. I am happy to keep them together if it doesn't matter tho. Just not sure if there's a formatting issue when pulled into the Django site?

**Comment by kallewesterling** [comment]
Technically speaking: as long as there are not multiple `## Challenge` sections in one lesson, there won't be a problem! Each `Lesson` can only handle one `Challenge`...

As for the pedagogical aspect, you can mix and match as you feel like for now. We might want to think, in the future, of making a distinction between more "theoretical" challenges and more hands-on ones (this is a good example of a [![](https://img.shields.io/github/labels/dhri-curriculum/data-literacies/wishlist)](../labels/wishlist) item, to add to your repo). For now, I think just contextualizing the `Challenge` is enough, like, with the first words say something like: "As a reflective challenge, consider..." or something better worded (my brain is not working at 100% right now)!

**Comment by dyoong** [comment]
Cool. Does the `Solution` have to be titled as so? Currently I've renamed it as `An Example` only cause it's strange to say that my perspective is the solution, but if the site requires it to be renamed as solution I will be sure to rename it.

**Comment by kallewesterling** [comment]
Yeah, if it's not named `## Solution`, it won't be paired with the `## Challenge` in the ingestion. But: if you want to open an issue in django-app to be able to have a different heading for the challenge/solution pair, you can [do so](https://github.com/DHRI-Curriculum/django-app/issues/new)!

The ingestion script takes whatever is in a `## Challenge` section and in an optional `## Solution` section and puts that at the bottom of the lesson where they are located.. That means that it doesn't matter where in the lesson you'd place the challenge/solution pair, but they will be automatically moved for you.

**Comment by dyoong** [comment]
Good to know! I will rename the file for now and also open an issue on the Django app. Thanks for your help. (thumbs up)

**Comment by kallewesterling** [comment]
Perfect, thank you so much!
