### ISSUE TITLE
Database Repository

### ISSUE THREAD

**Issue by dyoong** [DHRI-Curriculum/data-literacies#4]
I wasn't sure if I should also be combining the readme.md file from the intro to database workshop to this version of the data and ethics workshop since we are now focusing more on that.

**Comment by kallewesterling** [comment]
Thank you for opening this issue @dyoong. Sorry that it has taken until now for me to add a comment here. I have relayed this question to @lmrhody for now but since we're approaching the end of this sprint, we might just want to add this to `sprint 2` for this workshop. I'll add a label to make sure it's on our radar.
